[18.0] [IMP] web_m2x_options: Migration to 18.0
chaule97/web pull request #1
Opened 2024-10-07 08:49 UTC by chaule97

- I update the JavaScript code to follow the ECMAScript

2024-10-11 05:24 UTC, xaviedoanhduy commented
Hello @chaule97 Are you confused about the name of the PR? 
It should be [18.0][MIG] or [18.0] [IMP]?

2024-10-11 07:22 UTC, xaviedoanhduy commented on web_m2x_options/static/src/components/base.xml
> +        owl="1"
```suggestion
```

> Remove owl="1" from OWL templates, as it's not needed anymore as all of them are OWL now. Reference: https://github.com/odoo/odoo/pull/130467. Application of this removal in Odoo core: https://github.com/odoo/odoo/pull/141383.

2024-10-11 08:22 UTC, xaviedoanhduy requested changes

2024-10-11 08:22 UTC, xaviedoanhduy commented on web_m2x_options/static/src/components/base.xml
> +        owl="1"
```suggestion
```

> Remove owl="1" from OWL templates, as it's not needed anymore as all of them are OWL now. Reference: https://github.com/odoo/odoo/pull/130467. Application of this removal in Odoo core: https://github.com/odoo/odoo/pull/141383.

2024-10-11 08:22 UTC, xaviedoanhduy commented on web_m2x_options/static/src/components/base.xml
> +        owl="1"
```suggestion
```
the same above

2024-10-11 08:22 UTC, xaviedoanhduy commented on web_m2x_options/static/src/components/form.esm.js
> +/** @odoo-module **/
```suggestion
```
no need for /** @odoo-module */ anymore (`https://github.com/odoo/odoo/pull/142858`)

2024-10-11 08:22 UTC, xaviedoanhduy commented on web_m2x_options/static/src/components/form.esm.js
> +        const limit = parseInt(ir_options["web_m2x_options.field_limit_entries"], 10);
very easy to broken! if the value in the `parseInt` does not return a numeric character.

2024-10-11 08:22 UTC, xaviedoanhduy commented on web_m2x_options/static/src/components/form.esm.js
> +        super.setup(...arguments);
```suggestion
        super.setup();
```

2024-10-11 08:28 UTC, xaviedoanhduy commented
btw, could you squash commits? 
https://github.com/OCA/maintainer-tools/wiki/Merge-commits-in-pull-requests

2024-10-11 08:50 UTC, xaviedoanhduy commented
I get this error in console log when install module `website`:
```
Uncaught Error: Error while loading "@mail/views/web/fields/many2many_tags_email/many2many_tags_email":
Error: Invalid object: unknown key 'm2mOptionsPropsCreate', unknown key 'm2mOptionsPropsCreateEdit', unknown key 'm2mOptionsPropsLimit', unknown key 'm2mOptionsPropsSearchMore', unknown key 'm2mOptionsProps'
    at ModuleLoader.startModule (web.assets_web.min.js:17:225)
    at ModuleLoader.startModules (web.assets_web.min.js:16:57)
    at ModuleLoader.addJob (web.assets_web.min.js:13:39)
    at ModuleLoader.define (web.assets_web.min.js:12:127)
    at web.assets_web.min.js:16304:6
```
![image](https://github.com/user-attachments/assets/16936757-8b26-412d-adba-9a8185d46149)

2024-10-14 05:15 UTC, chaule97 commented
> I get this error in console log when install module `website`:
> 
> ```
> Uncaught Error: Error while loading "@mail/views/web/fields/many2many_tags_email/many2many_tags_email":
> Error: Invalid object: unknown key 'm2mOptionsPropsCreate', unknown key 'm2mOptionsPropsCreateEdit', unknown key 'm2mOptionsPropsLimit', unknown key 'm2mOptionsPropsSearchMore', unknown key 'm2mOptionsProps'
>     at ModuleLoader.startModule (web.assets_web.min.js:17:225)
>     at ModuleLoader.startModules (web.assets_web.min.js:16:57)
>     at ModuleLoader.addJob (web.assets_web.min.js:13:39)
>     at ModuleLoader.define (web.assets_web.min.js:12:127)
>     at web.assets_web.min.js:16304:6
> ```
> 
> ![image](https://private-user-images.githubusercontent.com/90429015/375690953-16936757-8b26-412d-adba-9a8185d46149.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjg4ODMxMjksIm5iZiI6MTcyODg4MjgyOSwicGF0aCI6Ii85MDQyOTAxNS8zNzU2OTA5NTMtMTY5MzY3NTctOGIyNi00MTJkLWFkYmEtOWE4MTg1ZDQ2MTQ5LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEwMTQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMDE0VDA1MTM0OVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWMyNjA3Mjc1OTdlOTRhZjAxZGVhOGJhMjc2NTMxNmU0MWRiMWQ2MGY4MjcyNjU0OTk4ZWRiNjc0NjFmYzliMzAmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.qhKsAwvqQVsxR4yQKIlnXYLg69vnWpib0FYsLxyGNdk)

you can read it, this issue still has no method

2024-10-14 05:17 UTC, chaule97 commented on web_m2x_options/static/src/components/form.esm.js
> +        const limit = parseInt(ir_options["web_m2x_options.field_limit_entries"], 10);
10 is default if ir_options["web_m2x_options.field_limit_entries"] can't get number

2024-10-14 05:30 UTC, closed without merging